services:
  ollama:
    container_name: ollama_dev
    image: ollama/ollama:latest
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  vibecheck:
    container_name: vibecheck_dev
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      # Mount source code for hot reload (air watches these files)
      - .:/app
      - go-modules:/go/pkg/mod
    working_dir: /app
    environment:
      # Storage configuration
      VIBECHECK_STORAGE_PATH: ${VIBECHECK_STORAGE_PATH:-/app/storage}
      VIBECHECK_STORAGE_TTL: ${VIBECHECK_STORAGE_TTL:-24h}
      # Debug mode (1 = enabled, 0 = disabled)
      VIBECHECK_DEBUG: ${VIBECHECK_DEBUG:-1}
      # Go runtime for development
      GODEBUG: ${GODEBUG:-}
      GOMODCACHE: /go/pkg/mod
      # Ollama configuration
      OLLAMA_HOST: ollama:11434
    ports:
      - ${VIBECHECK_MCP_PORT:-8080}:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  go-modules:
  ollama:
