services:
  ollama:
    container_name: ollama_local
    image: ollama/ollama:latest
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - 11434:11434
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  vibecheck:
    container_name: vibecheck_local
    build:
      context: .
      dockerfile: docker/Dockerfile.local
    environment:
      OLLAMA_HOST: host.docker.internal:11434
    volumes:
      - ~/.cache/ms-playwright:/ms-playwright
    depends_on:
      ollama:
        condition: service_healthy
