# Modules caching
FROM golang:1.25-bookworm AS modules
ARG DIR
WORKDIR ${DIR}

COPY go.mod go.sum ${DIR}/
RUN go mod download

# Builder
FROM golang:1.25-bookworm AS builder

RUN go install github.com/air-verse/air@latest

ARG DIR
WORKDIR ${DIR}

COPY . .

# Command to run air
ENV GOFLAGS="-buildvcs=false"
ENTRYPOINT ["air", "-c", ".air.toml"]